### ISSUE TITLE
Minification fails when using css variables inside style

### ISSUE THREAD

**Issue by lukapopijac** [asyncLiz/rollup-plugin-minify-html-literals#14]
Breaks with this message:
> (!) Plugin minify-html-literals: splitHTMLByPlaceholder() must return same number of strings as template parts

input.js:
```js
html`
	<div style="--xyz: ${a};">
	</div>
`;
```

**Comment by asyncLiz** [comment]
I added this error to the description of https://github.com/asyncLiz/minify-html-literals/issues/23 to investigate there as well, since it's related to the same issue of using replacements in the `style` attribute.

My recommended workaround in the meantime is the same: I'd suggest using a `<style>` tag or `css` template first. If you can't and must use the style attribute, I'd recommend replacing the entire style attribute with a replacement.
