### ISSUE TITLE
👆 Maintenance status of this project?

### ISSUE THREAD

**Issue by tirithen** [asyncLiz/rollup-plugin-minify-html-literals#32]
Hi! As there are several projects using this npm package, but it not having a release for over 3 years now, I wonder, is there a plan for how maintenance could be passed on to more active developers?

Forks has even started to popup with a separate package name like https://github.com/ouweiya/rollup-plugin-minify-html-literals-v3 .

As Rollup continues to make major releases this package needs to keep releasing at least once for each major release.

Any thoughts about how this could be solved moving on?

**Comment by tirithen** [comment]
There is also a pull request with simliar updates to the forked package https://github.com/asyncLiz/rollup-plugin-minify-html-literals/pulls

**Comment by asyncliz** [comment]
Hi! Thank you so much for using this and I apologize for not being able to maintain it since I started working on Lit 😣

We're moving this project into [lit labs](https://github.com/lit/lit/tree/main/packages/labs/rollup-plugin-minify-html-literals) so the Lit team and community can maintain and update it better than lil ol me. See https://github.com/lit/lit/issues/4273 for getting it released to npm as `@lit-labs/rollup-plugin-minify-html-literals`.

**Comment by tirithen** [comment]
@asyncLiz thank you so much for the response, and nice to see it moved to lit which is anyway one of the core dependencies in the project where I needed the updated version, I'll give that package a try soon.

Maybe it would be possible to archive this package, or at least reference `@lit-labs/rollup-plugin-minify-html-literals` in the `README.md` of this repo to help anyone else needing a newer version. :-)

**Comment by yhaiovyi-tripactions** [comment]
`@lit-labs/rollup-plugin-minify-html-literals` was never published :(
