### ISSUE TITLE
issue with self-closing tags

### ISSUE THREAD

**Issue by WebReflection** [asyncLiz/rollup-plugin-minify-html-literals#4]
Hello there! I've realized the produced out, given the following input, might create unexpected results:

```js
const scope = {};
render(el, html`<App .scope=${scope}/>`);
```

The observed result is that `<App .scope=${scope}/>` becomes `<App .scope=${scope}/ ></App>`, but things get even more interesting when there is a space after `scope`:

```js
const scope = {};
render(el, html`<App .scope=${scope} />`);
```
That would be converted into `<App .scope=${scope}>`, removing the self closing tag, hence breaking libraries capable of dealing with it, such as _lighterhtml_, _neverland_, or _heresy_, which is kinda of a bummer, because by design these libraries simplify Custom Elements tag writing, without needing to close empty elements, either as _divs_, used to decorate, or _custm_elements_.

Unfortunately, this means I should suggest to avoid this plugin with those libraries, as it can have undesired side-effects if people write simplified HTML tags, without these needing necessarily to be void tags.

Is it reasonable to ask to add an option to leave the self closing `/>`, either with, or without a space before, untouched? That would make this awesome tool usable to produce minified components for pretty much all of my libraries.

Thanks in advance for any sort of outcome, and for eventually considering adding this extra option.

**Comment by asyncLiz** [comment]
Let's answer the closing slash space issue first. The template string is parsed as HTML, and everything after an attribute's `=` is treated as part of the attribute, with the exception of opening and closing quotes.

Your attribute is `.scope=${scope}/` in this case. Even though we're in a template literal, we're still parsing the substitution as an "attribute". To fix this, either add a space between the self closing slash, or use quotes to denote what is and is not part of the attribute.

```html
<App .scope="${scope}"/>
<!-- or -->
<App .scope=${scope} />
```

The second part of your problem is actually pretty simple! We pass along the template string to [html-minifier](https://www.npmjs.com/package/html-minifier), and it has an option to preserve the self-closing slash that is false by default.

```js
export default {
  entry: 'index.js',
  dest: 'dist/index.js',
  plugins: [
    minifyHTML({
      options: {
        minifyOptions: { keepClosingSlash: true }
      }
    })
  ]
};
```

**Comment by WebReflection** [comment]
thanks for suggesting the `html-minifier` workaround for my issue, it's definitively something handy to know (and apologies I should've read more documentation regarding that), however, the needed for quotes in template literals doesn't sound too good to me, as template literals can easily detect chunks of the template before an attribute `/\s\w=['"]?$/` but what you are saying is that template literals have basically no role in this minifier, used (AFAIK) mostly with template literals capable libraries ... so, let's focus on the first issue, as it's something that seems to be addressable in here: would sanitizing literals via `html.replace(/=(\$\{[\S\s]+\})([\s/])/g, '="$1$2"')` before passing it to the HTML parser be an option?

**Comment by asyncLiz** [comment]
It isn't a template literal issue, it's an HTML formatting issue. The HTML that you wrote has a problem with it because you're not including a space between the attribute and the self closing tag. Take the following example:

```html
<br test=foo/>

<!-- We want <br test="foo" />, but we get -->
<br test="foo/">
```

You'll run into the same problem if you don't include a space between attributes.

```html
<br test=foobar=baz>

<!-- We want <br test="foo" bar="baz">, but we get -->
<br test="foobar=baz">
```

An exception to the required space is when an attribute is surrounded by quotes.

```html
<br foo="bar"/>
<!-- correctly parses as -->
<br foo="bar" />

<br test="foo"bar="baz">
<!-- correctly parses as -->
<br test="foo" bar="baz">
```

So there are two solutions to the incorrectly formatted HTML. Add a space between attributes and closing tags (my personal preferred option), or use quotes if you do not want to add spaces between attributes and closing tags.

You don't _need_ quotes around the attributes' values. Adding spaces around attributes will suffice.

**Comment by WebReflection** [comment]
> It isn't a template literal issue, it's an HTML formatting issue.

I respectfully disagree, because the template tag, in template literals content, defines the boundaries of the attribute already, when no quotes are around, example:

```js
const tag = (template, ...values) => template.join('""');
tag`<p test=${1}/>`;
// <p test=""/>
```

the `${1}` part is a hole in the template aiming at defining a single attribute (not sparse, for spares you need mandatory quotes around), so it seems a bit odd my libraries can deal with that (they sanitize the input taking care of that parts too) but a minifier used to minify template literals "believes" a slash after a well defined template hole should be considered as part of the attribute.

I can warn/educate my libraries users to put a space and use the suggested option to avoid surprises, but it's been years I haven't had issues with template literals self-closing tags until I've tried to use this handy tool, so that telling all my libraries users "_hey, it's been fan believing what you see as a hole has to stay away from self-closing tags until now, but guess what ... ?_", which is why I wonder if there's any plan to avoid this easy-for-users _footgun_, but I guess I've already received the answer.

Best Regards.

**Comment by WebReflection** [comment]
P.S. do you know if there is any linter/tool capable of warning users that in JS used template literals to define some attribute value, and they self-closed a tag too early, without a space? That **might** be a better solution, to avoid footguns, when this minifier is used. Thank you.

**Comment by asyncLiz** [comment]
The template literal substitution does not define the boundaries of _only_ attributes.

```js
html`
  <div attr=${'value'}>
    ${html`<span>${'Hello World'}</span>`}
  </div>
`;
```
In the above example, we have three substitutions for an attribute, markup, and inner text. We cannot assume that we can join all template literal parts with quotes. If we did, we'd get this.
```html
<div attr="value">
  "<span>"Hello World"</span>"
</div>
```

That's incorrect, and would add extra quotes to our text. In other words, in order to _only_ add the double quotes to the attribute substitution, we need to know _what_ a template's substitution is for. That requires parsing the HTML to understand that it's for an attribute or something else.

That logic won't easily work with this library. To show why, let me explain what this library does.

The way this library works is by looking at the HTML as a whole, not in parts. For example, given the following string:

```js
html`
  <div attr="${'foo'}">
    Bar
  </div>
`
```
How should it be minified? It's obvious to us looking at the whole thing. We can get rid of some whitespace and the double quotes aren't needed. Having that context is also important to minifiers. They can't accurately minify parts of html.

```js
const firstPart = `
  <div attr="`;

const secondPart = `">
    Bar
  </div>
`;
```
Both of those are invalid HTML and cannot be minified without the full context. To get that context, this library treats them as a single string of HTML.
```js
const fakeHTMLToMinify = `
  <div attr="@TEMPLATE_EXPRESSION">
    Bar
  </div>
`;
```

That string is valid HTML and can be minified. Note that the library doesn't care what's _inside_ the substitution, or even where it occurs.
```js
const minified = `<div attr=@TEMPLATE_EXPRESSION>Bar</div>`;
```
Finally, we take each substitution marker and replace it with the original JS code to get the final result: untouched JS code where only the strings are minified.
```js
html`<div attr=${'foo'}>Bar</div>`;
```

The performance of this library comes from its simplicity. It doesn't parse the HTML string or care about what the template substitution is for (be it an attribute, more HTML, text, or other library-specific situations like lit-html's event listeners).

It's not worth the additional cost to determine how to differentiate and handle the position of a template substitution, especially when the solution [can be considered a best practice](https://stackoverflow.com/questions/462741/space-before-closing-slash).

**Comment by WebReflection** [comment]
> in order to only add the double quotes to the attribute substitution, we need to know what a template's substitution is for. That requires parsing the HTML to understand that it's for an attribute or something else.

that's actually what [domsanitizer](https://github.com/WebReflection/domsanitizer) does in my libraries, and the join by quotes was just an example.

A hole has a context, and when it comes to HTML it's either within attributes, or content.

That means, that a simple check for templates chunks, such as `chunk[i][0] === '/'`, could indicate the case when a hole has been used to define an attribute right *before* the self closing tag, if the previous part of the template matches `/\s\w=/.test(chunk[i - 1])`, or if the whole string before passes `/<\w\s[^>]*?\w=/.test(template.slice(0, i - 1).join(''))`, with all the caveats related to the `\w` or `\s` covered in _domsanitizer_ to ensure valid checks.

> That logic won't easily work with this library.

Yeah, after forking it, I've realized it's not something easy to deal it, I'd also would like to use this occasion to mention this library has tons of vulnerabilities due its dependencies:

```
found 83 vulnerabilities (3 low, 4 moderate, 74 high, 2 critical)
```

but after updating them all, it didn't work due `TSError: ⨯ Unable to compile TypeScript` issues, but i don't want to go too much off-topic here.

> How should it be minified?

Differently from JS minifiers, HTML minifiers easily cause side-effects to libarries trusting the exact output they put in the template literal.

The `childNodes[0]` is not an empty node anymore, and I don't even know if the minifier drops comments, which might be used for any kind of purpose, as _hyperHTML_, _lighterhtml_, and also _lit-html_ do, so it's all about compromises.

In a template literal **context**, specially when it comes to minify the code, `<p what=${'ever'}/>` is the most compact way to represent a `<P>`, with an attribute `what`, defined by `${...}` hole, and my libs can deal with the self closing tag, as these use template tag chunks to understand what is what, and where (or in case of _domsanitizer_, the lib knows what to look for around attributes).

> The performance of this library comes from its simplicity.

I don't personally care much about performance of tools that don't run in the Web, as runtime, and I believe any pre/post processor goal is to be performant enough, and try to avoid least surprises.

This minifer, as handy as it is, violate the "_least surprise_" concept when it comes to minify template literals, because it changes completely the developer intent, without considering template well defined holes, as something a part that has nothing to do with the surrounding markup.

If I write this:

```js
html`<p hole=${123}/>`
```

I would never expect a hole with value different from `123`, as well as I would never expect the `hole` attribute to have value `${123}/` because the context matters, and in the template literals world that has no meaning whatsoever, but it can cause issues to any library that would instead deal with holes, chunks, and layout, and expects that anything around holes, in attributes context, without quotes around, is a well defined attribute hole value.

I hope I've explained my disagreement more now, and it's OK if this tool won't ever manage to understand what's a template literal hole about, within attribute scopes.

Thanks for your time though, I've appreciated your insights, I hope you somehow understood where I came from too 👋
